### ISSUE TITLE
Configuration in .emacs needed even when installed from melpa

### ISSUE THREAD

**Issue by GregorZattler** [pft/mingus#11]
I installed mingus from melpa.  I have to have 
(autoload 'mingus "mingus" nil t)
in my .emacs otherwise function mingus is void.  

And without 
(add-to-list 'load-path "/path/where/mingus/resides")
nothing happens with M-X mingus 
(as opposed to (mingus) C-x C-e in scratch buffer).

Is this as it should be?

Thanks, "mingus" is a great name for a mpd client.

**Comment by pft** [comment]
Hi Gregor,

Thanks for your report.

I added an ;;;###autoload magic comment to the file just now. I think this should do the trick once Melpa has updated this package.

**Comment by GregorZattler** [comment]
Hi Niels,
* Niels Giesen <notifications@github.com> [14. Oct. 2015]:
> I added an ;;;###autoload magic comment to the file just now. I
> think this should do the trick once Melpa has updated this
> package.

I upgraded today and it indeed does work now without
customization.  Thank you.

Actually mpd is startet at system startup.  If there was no other
interaction with mpd before M-x mingus does nothing, but M-x
mingus-browse works.  Only later if mpd does not play music M-x
mingus shows the mingus browser.  This is documented in the help
text but in the Getting Started section on line 126.  Perhaps it
should be more prominent?  Or Mx mingus   should start
mingus-browse if nothing else would happen?

Anyways: Thanks for mingus, it helps me a lot since I was not
able to tame EMMS.

Ciao, Gregor
-- 
 -... --- .-. . -.. ..--.. ...-.-

**Comment by pft** [comment]
M-x mingus always opens the *Mingus* buffer, which is the playlist buffer.
M-x mingus-browse opens the *Mingus Browser* buffer.

I do not want to open the browser buffer when the playlist is empty, as
this would be confusing in my opinion, but perhaps showing some message
could be nice (such as "press 1 for help, 3 to select music"). Have to give
this some more thought though.

On Fri, Oct 16, 2015 at 1:37 PM, GregorZattler <notifications@github.com>
wrote:

> Hi Niels,
> * Niels Giesen <notifications@github.com> [14. Oct. 2015]:
> > I added an ;;;###autoload magic comment to the file just now. I
> > think this should do the trick once Melpa has updated this
> > package.
>
> I upgraded today and it indeed does work now without
> customization. Thank you.
>
> Actually mpd is startet at system startup. If there was no other
> interaction with mpd before M-x mingus does nothing, but M-x
> mingus-browse works. Only later if mpd does not play music M-x
> mingus shows the mingus browser. This is documented in the help
> text but in the Getting Started section on line 126. Perhaps it
> should be more prominent? Or Mx mingus should start
> mingus-browse if nothing else would happen?
>
> Anyways: Thanks for mingus, it helps me a lot since I was not
> able to tame EMMS.
>
> Ciao, Gregor
> --
> -... --- .-. . -.. ..--.. ...-.-
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pft/mingus/issues/11#issuecomment-148691792>.
>



-- 
http://pft.github.com

**Comment by pft** [comment]
It's funny, this already happens
