### ISSUE TITLE
Symbol's value as variable is void: xfade

### ISSUE THREAD

**Issue by micah** [pft/mingus#12]
I'm trying to increase and decrease my volume with mingus, but I get the above error - do I need some external package/program installed to do this? 

thanks!

**Comment by pft** [comment]
I just pushed a quick fix for that issue.

Note to self: get rid of `mingus-bind-plist' -- it was a bad idea.

**Comment by micah** [comment]
Niels Giesen <notifications@github.com> writes:

> I just pushed a quick fix for that issue.
>
> Note to self: get rid of `mingus-bind-plist' -- it was a bad idea.

great, that works!

thanks a lot!
