### ISSUE TITLE
Mingus not showing info in modeline

### ISSUE THREAD

**Issue by micah** [pft/mingus#13]
I've got Mingus Mode Always Modeline set to 'on' in Customize Group: Mingus Mode Line, but I see no information about mingus in my modeline. 

I'm happy to provide any information to help debug this! I'm using mingus version 0.33 and emacs 24.5.

thanks!

**Comment by pft** [comment]
Hi, I am fixing this in the mopidy branch (but that branch still has a problem when you close mpd in that mingus keeps trying to reconnect).

**Comment by micah** [comment]
> Hi, I am fixing this in the mopidy branch (but that branch still has a problem when you close mpd in that mingus keeps trying to reconnect).

Excellent, looking forward to giving it a spin.

Mingus is great!

**Comment by pft** [comment]
Mingus now keeps timer cancelled on connection error. Going to merge mopidy back to master.
