### ISSUE TITLE
documentation fix: mention IP address format

### ISSUE THREAD

**Issue by tidux** [pft/mingus#25]
The page currently shown for `M-x mingus-customize` does not mention that enclosing double quotes are needed for an IP address as the value in `mingus-mpd-host`.  The error thrown is not particularly helpful either, but that's more of an Emacs issue.

**Comment by pft** [comment]
I think I fixed this by initializing the variable to a string value in commit https://github.com/pft/mingus/commit/db0f631cfb36a555e3f984803d48f48cf5afc0bb.

Because the default value could be nil, customization did not enforce the value in the box to be interpreted as a string.
