### ISSUE TITLE
all queries result in `Wrong type argument: char-or-string-p, nil`

### ISSUE THREAD

**Issue by emacsomancer** [pft/mingus#29]
Running on Arch Linux, latest stable Emacs, mingus from Melpa.

When I try any sort of query, it hesistates for about 5-10 secs and then tells me:

`Wrong type argument: char-or-string-p, nil`

**Comment by vuori** [comment]
This seems to happen with Helm when `helm-mode` is enabled.  As a workaround, add `(add-to-list 'helm-completing-read-handlers-alist '(mingus-query . nil))` to your init file.

**Comment by emacsomancer** [comment]
I tried with `(add-to-list 'ivy-completing-read-handlers-alist '(mingus-query . nil))` (since I'm not using `helm`), but I'm still getting the same error.

**Comment by pft** [comment]
I cannot reproduce this, either with or without helm-mode turned on.

**Comment by pft** [comment]
And then I could... I was using mopidy, which did not give me an issue (just a warning in the terminal).
It was an issue with the completion code. Commit 4223be618 (and its parent) should fix it.

**Comment by emacsomancer** [comment]
Yes, I am able to `query` successfully now.

Thank you!
