### ISSUE TITLE
Major modes

### ISSUE THREAD

**Issue by seagle0128** [pft/mingus#41]
Thanks for bringing mingus back to Emacs 28+!

May I know why not using `define-derived-mode` to define the major modes? It will make the code simple and clean.

https://github.com/pft/mingus/blob/aca914bfd81e18a37b2cc91f8ad219719a46c108/mingus.el#L2080-L2105

**Comment by pft** [comment]
For one thing, they are major modes. And I don't remember what went on in my head that long ago.

If you can rewrite it cleaner with the same, or better, effect, be my guest.

**Comment by seagle0128** [comment]
Sorry, my bad! Should be `define-derived-mode` to define the major modes. I updated the descriptions.

**Comment by pft** [comment]
Sure, go ahead.
