### ISSUE TITLE
define-fringe-bitmap is not always available

### ISSUE THREAD

**Issue by dholm** [pft/mingus#5]
When Emacs is built without Cocoa or X on MacOS X it doesn't include the function ```define-fringe-bitmap``` causing Mingus to fail during load.  The same issue was identified in flycheck/flycheck#57.

    Debugger entered--Lisp error: (void-function define-fringe-bitmap)
    (define-fringe-bitmap (quote mingus-NP-fringe) [128 192 224 240 248 252 248 240 224 192 128])
    ad-Orig-require(mingus nil nil)
    require(mingus)                                                                                                    
    eval-buffer(#<buffer  *load*-493821> nil "/Users/dholm/.emacs.d/el-get/mingus/mingus-stays-home.el" nil t)  ; Reading at buffer position 6310
    load-with-code-conversion("/Users/dholm/.emacs.d/el-get/mingus/mingus-stays-home.el" "/Users/dholm/.emacs.d/el-get/mingus/mingus-stays-home.el" nil t)
    ad-Orig-require(mingus-stays-home nil nil)
    require(mingus-stays-home)

**Comment by pft** [comment]
Guarding added in commit e03483a17f1c7e8c4ba684be428e0520e0b31b05,
