### ISSUE TITLE
Configure browse - show genres?

### ISSUE THREAD

**Issue by houshuang** [pft/mingus#6]
This is absolutely beautiful, I was looking for a nice way to play music from Emacs with ID3 tags etc. However, is there a way to configure the information shown in browse mode - I usually prefer to start from genre, rather than artist/album? I tried digging around in the documentation/code, but I couldn't find anything.

Other than that, awesome. ncmpcpp works great in terminal, but it's nice to not have to leave Emacs (and ncmpcpp in ansi-term looks quite jumpy) - and of course with mpd, we can have both! :)

**Comment by pft** [comment]
Hi houshang, do you know you can search by genre? That's M-x mingus-query, or simply Q from a mingus buffer.
