### ISSUE TITLE
Upload to Melpa or marmalade

### ISSUE THREAD

**Issue by IvanMalison** [pft/mingus#9]
Is there a reason this hasnt been done yet?

**Comment by pft** [comment]
A few things:
- Lack of time.
- Need to contact author of libmpdee.el to put that library in separate package in one of said repositories (though I believe I did that before (ages ago), yet cannot find any trace of it in my mail).

Note I am keen to the idea and you are very welcome to help out here.

**Comment by IvanMalison** [comment]
Melpa is super easy. I'm totally willing to make both recipes... is there a canonical repository for libmpdee, or would it be appropriate to use the one stored in this repository?

**Comment by pft** [comment]
I do not know of a canonical repository. Maybe it's best to set one up? [MPD Wikia](http://mpd.wikia.com/wiki/Client:Libmpdee) and [EmacsWiki](http://www.emacswiki.org/emacs/MusicPlayers) state there used to be an [svn repository](https://svn.musicpd.org/libmpdee/trunk/), but it is dead. 
The email of the author (R.Ramkumar) can be found inside libmpdee.el. Perhaps he still has a personal copy of the repository.
Once there is a canonical repository, I can also remove the file from this repository.

**Comment by andyetitmoves** [comment]
mpd used to have a canonical repo for libmpdee but I had been inactive for a while and looks like that had been removed as unmaintained. I had the repo locally and have now made it available as andyetitmoves/libmpdee, feel free to use it..

**Comment by noctuid** [comment]
@IvanMalison Is there a reason for not proceeding now that libmpdee is on melpa?

**Comment by IvanMalison** [comment]
Nope, lets do it!

**Comment by noctuid** [comment]
Actually, libmpdee should probably removed from here first (to avoid using `:files` just to ignore it).

@pft Since libmpdee has its own repo now, will you remove it from here?

**Comment by pft** [comment]
Done.

**Comment by noctuid** [comment]
Thanks! I made a pull request to fix the package data so that it will work with MELPA.

**Comment by noctuid** [comment]
Well it's on MELPA now :D, so this can be closed.

You might want to look at the suggestions Steve Purcell made for changes to mingus as well if you have the time.
